# Linking SVG to kanji (utf-8)

#### Since we already have kanji to SVG mapping
in ```../data_raw/kanji_to_svg_index.json```

- ```some_kanji_character``` -> ```svg_file_name.svg```

#### We need to reverse the mapping so we could find the kanji from SVG file naming
- ```svg_file_name.svg``` -> ```some_kanji_character```

#### We will have two way connection
- ```some_kanji_character``` <-> ```svg_file_name.svg```


##### From ```some_kanji_character``` we can find kanji information

In [18]:
import json

kanji_svg_mapping_path = "../data_raw/kanji_to_svg_index.json"

with open(kanji_svg_mapping_path) as f:
  mapping = json.load(f)
  f.close()

new_mapping = {}

for k, v in mapping.items():
  for s in v:
    new_mapping[s] = k

svg_to_kanji_mapping_path = "../data_raw/svg_to_kanji_index.json"

with open(svg_to_kanji_mapping_path, 'w+') as sf:
  dump = json.dumps(obj= new_mapping, indent=2, ensure_ascii=False) # ensure_ascii=False, will prevent kanji (non-ascii) to be converted to unicode escape
  sf.write(dump)
  sf.close()

In [20]:
with open(svg_to_kanji_mapping_path, 'r') as f:
  print(f.read())
  f.close()

{
  "00021.svg": "!",
  "0002c.svg": ",",
  "0002e.svg": ".",
  "00030.svg": "0",
  "00031.svg": "1",
  "00032.svg": "2",
  "00033.svg": "3",
  "00034.svg": "4",
  "00035.svg": "5",
  "00036.svg": "6",
  "00037.svg": "7",
  "00038.svg": "8",
  "00039.svg": "9",
  "0003a.svg": ":",
  "0003b.svg": ";",
  "0003f.svg": "?",
  "00041.svg": "A",
  "00042.svg": "B",
  "00043.svg": "C",
  "00044.svg": "D",
  "00045.svg": "E",
  "00046.svg": "F",
  "00047.svg": "G",
  "00048.svg": "H",
  "00049.svg": "I",
  "0004a.svg": "J",
  "0004b.svg": "K",
  "0004c.svg": "L",
  "0004d.svg": "M",
  "0004e.svg": "N",
  "0004f.svg": "O",
  "00050.svg": "P",
  "00051.svg": "Q",
  "00052.svg": "R",
  "00053.svg": "S",
  "00054.svg": "T",
  "00055.svg": "U",
  "00056.svg": "V",
  "00057.svg": "W",
  "00058.svg": "X",
  "00059.svg": "Y",
  "0005a.svg": "Z",
  "00061.svg": "a",
  "00062.svg": "b",
  "00063.svg": "c",
  "00064.svg": "d",
  "00065.svg": "e",
  "00066.svg": "f",
  "00067.svg": "g",
  "00068.svg": "h",
  "00069.svg": "i",
  "0006a.svg": "j",
  "0006b.svg": "k",
  "0006c.svg": "l",
  "0006d.svg": "m",
  "0006e.svg": "n",
  "0006f.svg": "o",
  "00070.svg": "p",
  "00071.svg": "q",
  "00072.svg": "r",
  "00073.svg": "s",
  "00074.svg": "t",
  "00075.svg": "u",
  "00076.svg": "v",
  "00077.svg": "w",
  "00078.svg": "x",
  "00079.svg": "y",
  "0007a.svg": "z",
  "02e89.svg": "⺉",
  "02e8c.svg": "⺌",
  "02e8d.svg": "⺍",
  "02e95.svg": "⺕",
  "02e97.svg": "⺗",
  "02ea1.svg": "⺡",
  "02ea2.svg": "⺢",
  "02ea4.svg": "⺤",
  "02ea6.svg": "⺦",
  "02ea8.svg": "⺨",
  "02ead.svg": "⺭",
  "02ec3.svg": "⻃",
  "02ecc.svg": "⻌",
  "02ecf.svg": "⻏",
  "02ed6.svg": "⻖",
  "03001.svg": "、",
  "03002.svg": "。",
  "03005.svg": "々",
  "03006.svg": "〆",
  "03041.svg": "ぁ",
  "03042.svg": "あ",
  "03043.svg": "ぃ",
  "03044.svg": "い",
  "03045.svg": "ぅ",
  "03046.svg": "う",
  "03047.svg": "ぇ",
  "03048.svg": "え",
  "03049.svg": "ぉ",
  "0304a.svg": "お",
  "0304b.svg": "か",
  "0304c.svg": "が",
  "0304d.svg": "き",
  "0304e.svg": "ぎ",
  "0304f.svg": "く",
  "03050.svg": "ぐ",
  "03051.svg": "け",
  "03052.svg": "げ",
  "03053.svg": "こ",
  "03054.svg": "ご",
  "03055.svg": "さ",
  "03056.svg": "ざ",
  "03057.svg": "し",
  "03058.svg": "じ",
  "03059.svg": "す",
  "0305a.svg": "ず",
  "0305b.svg": "せ",
  "0305c.svg": "ぜ",
  "0305d.svg": "そ",
  "0305e.svg": "ぞ",
  "0305f.svg": "た",
  "03060.svg": "だ",
  "03061.svg": "ち",
  "03062.svg": "ぢ",
  "03063.svg": "っ",
  "03064.svg": "つ",
  "03065.svg": "づ",
  "03066.svg": "て",
  "03067.svg": "で",
  "03068.svg": "と",
  "03069.svg": "ど",
  "0306a.svg": "な",
  "0306b.svg": "に",
  "0306c.svg": "ぬ",
  "0306d.svg": "ね",
  "0306e.svg": "の",
  "0306f.svg": "は",
  "03070.svg": "ば",
  "03071.svg": "ぱ",
  "03072.svg": "ひ",
  "03073.svg": "び",
  "03074.svg": "ぴ",
  "03075.svg": "ふ",
  "03076.svg": "ぶ",
  "03077.svg": "ぷ",
  "03078.svg": "へ",
  "03079.svg": "べ",
  "0307a.svg": "ぺ",
  "0307b.svg": "ほ",
  "0307c.svg": "ぼ",
  "0307d.svg": "ぽ",
  "0307e.svg": "ま",
  "0307f.svg": "み",
  "03080.svg": "む",
  "03081.svg": "め",
  "03082.svg": "も",
  "03083.svg": "ゃ",
  "03084.svg": "や",
  "03085.svg": "ゅ",
  "03086.svg": "ゆ",
  "03087.svg": "ょ",
  "03088.svg": "よ",
  "03089.svg": "ら",
  "0308a.svg": "り",
  "0308b.svg": "る",
  "0308c.svg": "れ",
  "0308d.svg": "ろ",
  "0308e.svg": "ゎ",
  "0308f.svg": "わ",
  "03090.svg": "ゐ",
  "03091.svg": "ゑ",
  "03092.svg": "を",
  "03093.svg": "ん",
  "03094.svg": "ゔ",
  "03095.svg": "ゕ",
  "03096.svg": "ゖ",
  "0309b.svg": "゛",
  "0309c.svg": "゜",
  "0309d.svg": "ゝ",
  "0309e.svg": "ゞ",
  "030a1.svg": "ァ",
  "030a2.svg": "ア",
  "030a3.svg": "ィ",
  "030a4.svg": "イ",
  "030a5.svg": "ゥ",
  "030a6.svg": "ウ",
  "030a7.svg": "ェ",
  "030a8.svg": "エ",
  "030a9.svg": "ォ",
  "030aa.svg": "オ",
  "030ab.svg": "カ",
  "030ac.svg": "ガ",
  "030ad.svg": "キ",
  "030ae.svg": "ギ",
  "030af.svg": "ク",
  "030b0.svg": "グ",
  "030b1.svg": "ケ",
  "030b2.svg": "ゲ",
  "030b3.svg": "コ",
  "030b4.svg": "ゴ",
  "030b5.svg": "サ",
  "030b6.svg": "ザ",
  "030b7.svg": "シ",
  "030b8.svg": "ジ",
  "030b9.svg": "ス",
  "030ba.svg": "ズ",
  "030bb.svg": "セ",
  "030bc.svg": "ゼ",
  "030bd.svg": "ソ",
  "030be.svg": "ゾ",
  "030bf.svg": "タ",
  "030c0.svg": "ダ",
  "030c1.svg": "チ",
  "030c2.svg": "ヂ",
  "030c3.svg": "ッ",
  "030c4.svg": "ツ",
  "030c5.svg": "ヅ",
  "030c6.svg": "テ",
  "030c7.svg": "デ",
  "030c8.svg": "ト",
  "030c9.svg": "ド",
  "030ca.svg": "ナ",
  "030cb.svg": "ニ",
  "030cc.svg": "ヌ",
  "030cd.svg": "ネ",
  "030ce.svg": "ノ",
  "030cf.svg": "ハ",
  "030d0.svg": "バ",
  "030d1.svg": "パ",
  "030d2.svg": "ヒ",
  "030d3.svg": "ビ",
  "030d4.svg": "ピ",
  "030d5.svg": "フ",
  "030d6.svg": "ブ",
  "030d7.svg": "プ",
  "030d8.svg": "ヘ",
  "030d9.svg": "ベ",
  "030da.svg": "ペ",
  "030db.svg": "ホ",
  "030dc.svg": "ボ",
  "030dd.svg": "ポ",
  "030de.svg": "マ",
  "030df.svg": "ミ",
  "030e0.svg": "ム",
  "030e1.svg": "メ",
  "030e2.svg": "モ",
  "030e3.svg": "ャ",
  "030e4.svg": "ヤ",
  "030e5.svg": "ュ",
  "030e6.svg": "ユ",
  "030e7.svg": "ョ",
  "030e8.svg": "ヨ",
  "030e9.svg": "ラ",
  "030ea.svg": "リ",
  "030eb.svg": "ル",
  "030ec.svg": "レ",
  "030ed.svg": "ロ",
  "030ee.svg": "ヮ",
  "030ef.svg": "ワ",
  "030f0.svg": "ヰ",
  "030f1.svg": "ヱ",
  "030f2.svg": "ヲ",
  "030f3.svg": "ン",
  "030f4.svg": "ヴ",
  "030f5.svg": "ヵ",
  "030f6.svg": "ヶ",
  "030f7.svg": "ヷ",
  "030f8.svg": "ヸ",
  "030f9.svg": "ヹ",
  "030fa.svg": "ヺ",
  "030fb.svg": "・",
  "030fc.svg": "ー",
  "030fd.svg": "ヽ",
  "030fe.svg": "ヾ",
  "0342c.svg": "㐬",
  "034c1.svg": "㓁",
  "0353e.svg": "㔾",
  "04e00.svg": "一",
  "04e01.svg": "丁",
  "04e03.svg": "七",
  "04e07.svg": "万",
  "04e08.svg": "丈",
  "04e09.svg": "三",
  "04e0a.svg": "上",
  "04e0b.svg": "下",
  "04e0d.svg": "不",
  "04e0e.svg": "与",
  "04e10.svg": "丐",
  "04e11.svg": "丑",
  "04e14-Kaisho.svg": "且",
  "04e14.svg": "且",
  "04e15.svg": "丕",
  "04e16.svg": "世",
  "04e17.svg": "丗",
  "04e18.svg": "丘",
  "04e19.svg": "丙",
  "04e1e.svg": "丞",
  "04e21.svg": "両",
  "04e26.svg": "並",
  "04e28.svg": "丨",
  "04e2a.svg": "个",
  "04e2d.svg": "中",
  "04e31.svg": "丱",
  "04e32.svg": "串",
  "04e36.svg": "丶",
  "04e38.svg": "丸",
  "04e39.svg": "丹",
  "04e3b-VtLst.svg": "主",
  "04e3b.svg": "主",
  "04e3c.svg": "丼",
  "04e3f.svg": "丿",
  "04e42.svg": "乂",
  "04e43.svg": "乃",
  "04e45.svg": "久",
  "04e4b-Kaisho.svg": "之",
  "04e4b.svg": "之",
  "04e4d.svg": "乍",
  "04e4e.svg": "乎",
  "04e4f.svg": "乏",
  "04e55.svg": "乕",
  "04e56.svg": "乖",
  "04e57-Kaisho.svg": "乗",
  "04e57.svg": "乗",
  "04e58-Kaisho.svg": "乘",
  "04e58.svg": "乘",
  "04e59.svg": "乙",
  "04e5d.svg": "九",
  "04e5e.svg": "乞",
  "04e5f.svg": "也",
  "04e62.svg": "乢",
  "04e71.svg": "乱",
  "04e73.svg": "乳",
  "04e7e-Kaisho.svg": "乾",
  "04e7e.svg": "乾",
  "04e80-Kaisho.svg": "亀",
  "04e80.svg": "亀",
  "04e82.svg": "亂",
  "04e85.svg": "亅",
  "04e86.svg": "了",
  "04e88.svg": "予",
  "04e89.svg": "争",
  "04e8a.svg": "亊",
  "04e8b.svg": "事",
  "04e8c.svg": "二",
  "04e8e.svg": "于",
  "04e91.svg": "云",
  "04e92.svg": "互",
  "04e94.svg": "五",
  "04e95.svg": "井",
  "04e98-Kaisho.svg": "亘",
  "04e98.svg": "亘",
  "04e99.svg": "亙",
  "04e9b-HzFst.svg": "些",
  "04e9b.svg": "些",
  "04e9c.svg": "亜",
  "04e9e.svg": "亞",
  "04e9f.svg": "亟",
  "04ea0-Kaisho.svg": "亠",
  "04ea0.svg": "亠",
  "04ea1-Kaisho.svg": "亡",
  "04ea1.svg": "亡",
  "04ea2-Kaisho.svg": "亢",
  "04ea2.svg": "亢",
  "04ea4.svg": "交",
  "04ea5-Kaisho.svg": "亥",
  "04ea5.svg": "亥",
  "04ea6-Kaisho.svg": "亦",
  "04ea6.svg": "亦",
  "04ea8-Kaisho.svg": "亨",
  "04ea8.svg": "亨",
  "04eab-Kaisho.svg": "享",
  "04eab.svg": "享",
  "04eac-Kaisho.svg": "京",
  "04eac.svg": "京",
  "04ead-Kaisho.svg": "亭",
  "04ead.svg": "亭",
  "04eae-Kaisho.svg": "亮",
  "04eae.svg": "亮",
  "04eb0-Kaisho.svg": "亰",
  "04eb0.svg": "亰",
  "04eb3-Kaisho.svg": "亳",
  "04eb3.svg": "亳",
  "04eb6-Kaisho.svg": "亶",
  "04eb6.svg": "亶",
  "04eba.svg": "人",
  "04ebb.svg": "亻",
  "04ec0.svg": "什",
  "04ec1.svg": "仁",
  "04ec2.svg": "仂",
  "04ec4.svg": "仄",
  "04ec6.svg": "仆",
  "04ec7.svg": "仇",
  "04eca.svg": "今",
  "04ecb.svg": "介",
  "04ecd.svg": "仍",
  "04ece.svg": "从",
  "04ecf.svg": "仏",
  "04ed4.svg": "仔",
  "04ed5.svg": "仕",
  "04ed6.svg": "他",
  "04ed7.svg": "仗",
  "04ed8.svg": "付",
  "04ed9.svg": "仙",
  "04edd.svg": "仝",
  "04ede.svg": "仞",
  "04edf.svg": "仟",
  "04ee3.svg": "代",
  "04ee4-Insatsu.svg": "令",
  "04ee4.svg": "令",
  "04ee5.svg": "以",
  "04eed.svg": "仭",
  "04eee.svg": "仮",
  "04ef0.svg": "仰",
  "04ef2.svg": "仲",
  "04ef6.svg": "件",
  "04ef7.svg": "价",
  "04efb.svg": "任",
  "04f01-HzFst.svg": "企",
  "04f01.svg": "企",
  "04f09-Kaisho.svg": "伉",
  "04f09.svg": "伉",
  "04f0a.svg": "伊",
  "04f0d.svg": "伍",
  "04f0e.svg": "伎",
  "04f0f.svg": "伏",
  "04f10.svg": "伐",
  "04f11-Kaisho.svg": "休",
  "04f11.svg": "休",
  "04f1a.svg": "会",
  "04f1c.svg": "伜",
  "04f1d.svg": "伝",
  "04f2f-Kaisho.svg": "伯",
  "04f2f.svg": "伯",
  "04f30.svg": "估",
  "04f34-HzFst.svg": "伴",
  "04f34.svg": "伴",
  "04f36-Insatsu.svg": "伶",
  "04f36.svg": "伶",
  "04f38-Kaisho.svg": "伸",
  "04f38.svg": "伸",
  "04f3a.svg": "伺",
  "04f3c.svg": "似",
  "04f3d.svg": "伽",
  "04f43-Kaisho.svg": "佃",
  "04f43.svg": "佃",
  "04f46-Kaisho.svg": "但",
  "04f46.svg": "但",
  "04f47-Kaisho.svg": "佇",
  "04f47.svg": "佇",
  "04f4d-Kaisho.svg": "位",
  "04f4d.svg": "位",
  "04f4e.svg": "低",
  "04f4f-VtLst.svg": "住",
  "04f4f.svg": "住",
  "04f50.svg": "佐",
  "04f51.svg": "佑",
  "04f53.svg": "体",
  "04f55.svg": "何",
  "04f57-Kaisho.svg": "佗",
  "04f57.svg": "佗",
  "04f59.svg": "余",
  "04f5a.svg": "佚",
  "04f5b.svg": "佛",
  "04f5c.svg": "作",
  "04f5d.svg": "佝",
  "04f5e.svg": "佞",
  "04f69.svg": "佩",
  "04f6f.svg": "佯",
  "04f70-Kaisho.svg": "佰",
  "04f70.svg": "佰",
  "04f73.svg": "佳",
  "04f75.svg": "併",
  "04f76.svg": "佶",
  "04f7b-MidFst.svg": "佻",
  "04f7b.svg": "佻",
  "04f7c-Kaisho.svg": "佼",
  "04f7c.svg": "佼",
  "04f7f.svg": "使",
  "04f83.svg": "侃",
  "04f86-Kaisho.svg": "來",
  "04f86.svg": "來",
  "04f88.svg": "侈",
  "04f8b.svg": "例",
  "04f8d.svg": "侍",
  "04f8f-Kaisho.svg": "侏",
  "04f8f.svg": "侏",
  "04f91-Kaisho.svg": "侑",
  "04f91.svg": "侑",
  "04f96-Kaisho.svg": "侖",
  "04f96.svg": "侖",
  "04f98-Kaisho.svg": "侘",
  "04f98.svg": "侘",
  "04f9b.svg": "供",
  "04f9d-Kaisho.svg": "依",
  "04f9d.svg": "依",
  "04fa0.svg": "侠",
  "04fa1.svg": "価",
  "04fab-Kaisho.svg": "侫",
  "04fab.svg": "侫",
  "04fad.svg": "侭",
  "04fae.svg": "侮",
  "04faf.svg": "侯",
  "04fb5-Kaisho.svg": "侵",
  "04fb5.svg": "侵",
  "04fb6.svg": "侶",
  "04fbf-Kaisho.svg": "便",
  "04fbf.svg": "便",
  "04fc2-Kaisho.svg": "係",
  "04fc2.svg": "係",
  "04fc3.svg": "促",
  "04fc4.svg": "俄",
  "04fca.svg": "俊",
  "04fce-Kaisho.svg": "俎",
  "04fce.svg": "俎",
  "04fd0-Kaisho.svg": "俐",
  "04fd0.svg": "俐",
  "04fd1-Kaisho.svg": "俑",
  "04fd1.svg": "俑",
  "04fd4-Kaisho.svg": "俔",
  "04fd4.svg": "俔",
  "04fd7.svg": "俗",
  "04fd8.svg": "俘",
  "04fda-Kaisho.svg": "俚",
  "04fda-KaishoVtLst.svg": "俚",
  "04fda.svg": "俚",
  "04fdb.svg": "俛",
  "04fdd-Kaisho.svg": "保",
  "04fdd.svg": "保",
  "04fdf.svg": "俟",
  "04fe1.svg": "信",
  "04fe3.svg": "俣",
  "04fe4-Kaisho.svg": "俤",
  "04fe4.svg": "俤",
  "04fe5-Kaisho.svg": "俥",
  "04fe5.svg": "俥",
  "04fee.svg": "修",
  "04fef-Kaisho.svg": "俯",
  "04fef.svg": "俯",
  "04ff1-Kaisho.svg": "俱",
  "04ff1.svg": "俱",
  "04ff3-MdFst.svg": "俳",
  "04ff3.svg": "俳",
  "04ff5-HzLst.svg": "俵",
  "04ff5.svg": "俵",
  "04ff6-HzFst.svg": "俶",
  "04ff6.svg": "俶",
  "04ff8.svg": "俸",
  "04ffa-Kaisho.svg": "俺",
  "04ffa.svg": "俺",
  "04ffe-Kaisho.svg": "俾",
  "04ffe.svg": "俾",
  "05005-Kaisho.svg": "倅",
  "05005.svg": "倅",
  "05006.svg": "倆",
  "05009.svg": "倉",
  "0500b.svg": "個",
  "0500d-Kaisho.svg": "倍",
  "0500d.svg": "倍",
  "0500f.svg": "倏",
  "05011-Kaisho.svg": "們",
  "05011.svg": "們",
  "05012-VtFst.svg": "倒",
  "05012.svg": "倒",
  "05014.svg": "倔",
  "05016.svg": "倖",
  "05019.svg": "候",
  "0501a.svg": "倚",
  "0501f-Kaisho.svg": "借",
  "0501f.svg": "借",
  "05021-Kaisho.svg": "倡",
  "05021.svg": "倡",
  "05023-Kaisho.svg": "倣",
  "05023.svg": "倣",
  "05024-Kaisho.svg": "値",
  "05024.svg": "値",
  "05025-Kaisho.svg": "倥",
  "05025.svg": "倥",
  "05026-Hyougai.svg": "倦",
  "05026.svg": "倦",
  "05028.svg": "倨",
  "05029-VtLst.svg": "倩",
  "05029.svg": "倩",
  "0502a-HzLst.svg": "倪",
  "0502a.svg": "倪",
  "0502b-Kaisho.svg": "倫",
  "0502b.svg": "倫",
  "0502c-Kaisho.svg": "倬",
  "0502c-KaishoHzFst.svg": "倬",
  "0502c.svg": "倬",
  "0502d.svg": "倭",
  "05036-Kaisho.svg": "倶",
  "05036.svg": "倶",
  "05039.svg": "倹",
  "05043-Kaisho.svg": "偃",
  "05043.svg": "偃",
  "05047.svg": "假",
  "05048-Kaisho.svg": "偈",
  "05048.svg": "偈",
  "05049.svg": "偉",
  "0504f-Kaisho.svg": "偏",
  "0504f.svg": "偏",
  "05050-Kaisho.svg": "偐",
  "05050.svg": "偐",
  "05055-Kaisho.svg": "偕",
  "05055.svg": "偕",
  "05056-Kaisho.svg": "偖",
  "05056.svg": "偖",
  "0505a.svg": "做",
  "0505c-Kaisho.svg": "停",
  "0505c.svg": "停",
  "05065.svg": "健",
  "0506c.svg": "偬",
  "05072-Kaisho.svg": "偲",
  "05072.svg": "偲",
  "05074-Kaisho.svg": "側",
  "05074.svg": "側",
  "05075-Kaisho.svg": "偵",
  "05075-KaishoHzFst.svg": "偵",
  "05075.svg": "偵",
  "05076-Kaisho.svg": "偶",
  "05076.svg": "偶",
  "05078.svg": "偸",
  "0507d.svg": "偽",
  "05080-Kaisho.svg": "傀",
  "05080.svg": "傀",
  "05085-Kaisho.svg": "傅",
  "05085.svg": "傅",
  "0508d-Kaisho.svg": "傍",
  "0508d.svg": "傍",
  "05091-Kaisho.svg": "傑",
  "05091.svg": "傑",
  "05098.svg": "傘",
  "05099-Insatsu.svg": "備",
  "05099-InsatsuKaisho.svg": "備",
  "05099-Kaisho.svg": "備",
  "05099.svg": "備",
  "0509a-Kaisho.svg": "傚",
  "0509a.svg": "傚",
  "050ac.svg": "催",
  "050ad-Kaisho.svg": "傭",
  "050ad.svg": "傭",
  "050b2-Kaisho.svg": "傲",
  "050b2.svg": "傲",
  "050b3.svg": "傳",
  "050b4.svg": "傴",
  "050b5-Kaisho.svg": "債",
  "050b5-KaishoVtLst.svg": "債",
  "050b5.svg": "債",
  "050b7-Kaisho.svg": "傷",
  "050b7.svg": "傷",
  "050be-Kaisho.svg": "傾",
  "050be.svg": "傾",
  "050c2.svg": "僂",
  "050c5-Hyougai.svg": "僅",
  "050c5-Jinmei.svg": "僅",
  "050c5.svg": "僅",
  "050c9.svg": "僉",
  "050ca.svg": "僊",
  "050cd-Kaisho.svg": "働",
  "050cd-KaishoVtLst.svg": "働",
  "050cd.svg": "働",
  "050cf.svg": "像",
  "050d1.svg": "僑",
  "050d5.svg": "僕",
  "050d6.svg": "僖",
  "050da-Kaisho.svg": "僚",
  "050da.svg": "僚",
  "050de.svg": "僞",
  "050e3-Kaisho.svg": "僣",
  "050e3.svg": "僣",
  "050e5.svg": "僥",
  "050e7-Kaisho.svg": "僧",
  "050e7.svg": "僧",
  "050ed-Kaisho.svg": "僭",
  "050ed.svg": "僭",
  "050ee-Kaisho.svg": "僮",
  "050ee-KaishoVtLst.svg": "僮",
  "050ee.svg": "僮",
  "050f5-Kaisho.svg": "僵",
  "050f5.svg": "僵",
  "050f9-Kaisho.svg": "價",
  "050f9.svg": "價",
  "050fb-Kaisho.svg": "僻",
  "050fb.svg": "僻",
  "05100.svg": "儀",
  "05101.svg": "儁",
  "05102-Kaisho.svg": "儂",
  "05102-KaishoVtLst.svg": "儂",
  "05102.svg": "儂",
  "05104-Kaisho.svg": "億",
  "05104.svg": "億",
  "05109.svg": "儉",
  "05112.svg": "儒",
  "05114.svg": "儔",
  "05115-Kaisho.svg": "儕",
  "05115-KaishoVt12.svg": "儕",
  "05115.svg": "儕",
  "05116-HzFst.svg": "儖",
  "05116.svg": "儖",
  "05118-VtFst.svg": "儘",
  "05118.svg": "儘",
  "0511a.svg": "儚",
  "0511f-Kaisho.svg": "償",
  "0511f.svg": "償",
  "05121-Kaisho.svg": "儡",
  "05121.svg": "儡",
  "0512a-Kaisho.svg": "優",
  "0512a.svg": "優",
  "05132-Hyougai.svg": "儲",
  "05132-HyougaiKaisho.svg": "儲",
  "05132-Kaisho.svg": "儲",
  "05132.svg": "儲",
  "05137-Kaisho.svg": "儷",
  "05137.svg": "儷",
  "0513a.svg": "儺",
  "0513b-VtLst.svg": "儻",
  "0513b.svg": "儻",
  "0513c-Kaisho.svg": "儼",
  "0513c-KaishoVt3.svg": "儼",
  "0513c.svg": "儼",
  "0513f.svg": "儿",
  "05140.svg": "兀",
  "05141.svg": "允",
  "05143.svg": "元",
  "05144.svg": "兄",
  "05145-Kaisho.svg": "充",
  "05145.svg": "充",
  "05146-MidFst.svg": "兆",
  "05146.svg": "兆",
  "05147.svg": "兇",
  "05148.svg": "先",
  "05149.svg": "光",
  "0514b.svg": "克",
  "0514c.svg": "兌",
  "0514d.svg": "免",
  "0514e-Hyougai.svg": "兎",
  "0514e-Jinmei.svg": "兎",
  "0514e.svg": "兎",
  "05150-Kaisho.svg": "児",
  "05150.svg": "児",
  "05152-HzLst.svg": "兒",
  "05152.svg": "兒",
  "05154.svg": "兔",
  "0515a.svg": "党",
  "0515c-Kaisho.svg": "兜",
  "0515c.svg": "兜",
  "05162.svg": "兢",
  "05165.svg": "入",
  "05168-VtLst.svg": "全",
  "05168.svg": "全",
  "05169.svg": "兩",
  "0516a.svg": "兪",
  "0516b.svg": "八",
  "0516c.svg": "公",
  "0516d-Kaisho.svg": "六",
  "0516d.svg": "六",
  "0516e.svg": "兮",
  "05171.svg": "共",
  "05173.svg": "关",
  "05175.svg": "兵",
  "05176-Kaisho.svg": "其",
  "05176.svg": "其",
  "05177-Kaisho.svg": "具",
  "05177.svg": "具",
  "05178-Kaisho.svg": "典",
  "05178-KaishoVtLst.svg": "典",
  "05178.svg": "典",
  "0517c.svg": "兼",
  "05180-Kaisho.svg": "冀",
  "05180.svg": "冀",
  "05182.svg": "冂",
  "05185.svg": "内",
  "05186.svg": "円",
  "05189.svg": "冉",
  "0518a.svg": "冊",
  "0518c.svg": "册",
  "0518d.svg": "再",
  "0518f.svg": "冏",
  "05190-Kaisho.svg": "冐",
  "05190.svg": "冐",
  "05191-Kaisho.svg": "冑",
  "05191-KaishoVtLst.svg": "冑",
  "05191.svg": "冑",
  "05192-Kaisho.svg": "冒",
  "05192.svg": "冒",
  "05193-Kaisho.svg": "冓",
  "05193.svg": "冓",
  "05195.svg": "冕",
  "05196.svg": "冖",
  "05197.svg": "冗",
  "05199.svg": "写",
  "051a0.svg": "冠",
  "051a2.svg": "冢",
  "051a4-Hyougai.svg": "冤",
  "051a4.svg": "冤",
  "051a5-Kaisho.svg": "冥",
  "051a5.svg": "冥",
  "051a6.svg": "冦",
  "051a8-Kaisho.svg": "冨",
  "051a8.svg": "冨",
  "051a9-HzLst.svg": "冩",
  "051a9.svg": "冩",
  "051aa-Kaisho.svg": "冪",
  "051aa.svg": "冪",
  "051ab.svg": "冫",
  "051ac.svg": "冬",
  "051b0.svg": "冰",
  "051b1.svg": "冱",
  "051b2.svg": "冲",
  "051b3.svg": "决",
  "051b4.svg": "冴",
  "051b5.svg": "况",
  "051b6.svg": "冶",
  "051b7-Insatsu.svg": "冷",
  "051b7.svg": "冷",
  "051bd.svg": "冽",
  "051c4-VtLst.svg": "凄",
  "051c4.svg": "凄",
  "051c5.svg": "凅",
  "051c6.svg": "准",
  "051c9-Kaisho.svg": "凉",
  "051c9.svg": "凉",
  "051cb.svg": "凋",
  "051cc.svg": "凌",
  "051cd-Kaisho.svg": "凍",
  "051cd.svg": "凍",
  "051d6.svg": "凖",
  "051db-Kaisho.svg": "凛",
  "051db.svg": "凛",
  "051dc-Kaisho.svg": "凜",
  "051dc.svg": "凜",
  "051dd-Kaisho.svg": "凝",
  "051dd.svg": "凝",
  "051e0.svg": "几",
  "051e1.svg": "凡",
  "051e6.svg": "処",
  "051e7.svg": "凧",
  "051e9-Kaisho.svg": "凩",
  "051e9.svg": "凩",
  "051ea-HzFst.svg": "凪",
  "051ea.svg": "凪",
  "051ed.svg": "凭",
  "051f0-Kaisho.svg": "凰",
  "051f0-KaishoVtLst.svg": "凰",
  "051f0.svg": "凰",
  "051f1.svg": "凱",
  "051f5.svg": "凵",
  "051f6.svg": "凶",
  "051f8.svg": "凸",
  "051f9.svg": "凹",
  "051fa.svg": "出",
  "051fd.svg": "函",
  "051fe.svg": "凾",
  "05200.svg": "刀",
  "05202.svg": "刂",
  "05203.svg": "刃",
  "05204.svg": "刄",
  "05206.svg": "分",
  "05207-Kaisho.svg": "切",
  "05207.svg": "切",
  "05208.svg": "刈",
  "0520a-Kaisho.svg": "刊",
  "0520a.svg": "刊",
  "0520b.svg": "刋",
  "0520e.svg": "刎",
  "05211.svg": "刑",
  "05214.svg": "刔",
  "05217.svg": "列",
  "0521d.svg": "初",
  "05224-Kaisho.svg": "判",
  "05224.svg": "判",
  "05225.svg": "別",
  "05227.svg": "刧",
  "05229-Kaisho.svg": "利",
  "05229.svg": "利",
  "0522a.svg": "刪",
  "0522e.svg": "刮",
  "05230-VtFst.svg": "到",
  "05230.svg": "到",
  "05233.svg": "刳",
  "05236.svg": "制",
  "05237.svg": "刷",
  "05238.svg": "券",
  "05239-Kaisho.svg": "刹",
  "05239.svg": "刹",
  "0523a-Kaisho.svg": "刺",
  "0523a.svg": "刺",
  "0523b-Kaisho.svg": "刻",
  "0523b.svg": "刻",
  "05243-Kaisho.svg": "剃",
  "05243.svg": "剃",
  "05244.svg": "剄",
  "05247-Kaisho.svg": "則",
  "05247.svg": "則",
  "0524a-Kaisho.svg": "削",
  "0524a.svg": "削",
  "0524b.svg": "剋",
  "0524c-Kaisho.svg": "剌",
  "0524c.svg": "剌",
  "0524d-Kaisho.svg": "前",
  "0524d.svg": "前",
  "0524f.svg": "剏",
  "05254-Kaisho.svg": "剔",
  "05254.svg": "剔",
  "05256-Kaisho.svg": "剖",
  "05256.svg": "剖",
  "0525b.svg": "剛",
  "0525d.svg": "剝",
  "0525e.svg": "剞",
  "05263.svg": "剣",
  "05264-Kaisho.svg": "剤",
  "05264-KaishoVt6.svg": "剤",
  "05264.svg": "剤",
  "05265-Jinmei.svg": "剥",
  "05265-Kaisho.svg": "剥",
  "05265.svg": "剥",
  "05269-Kaisho.svg": "剩",
  "05269.svg": "剩",
  "0526a.svg": "剪",
  "0526f-Kaisho.svg": "副",
  "0526f.svg": "副",
  "05270-Kaisho.svg": "剰",
  "05270.svg": "剰",
  "05271.svg": "剱",
  "05272-Kaisho.svg": "割",
  "05272-KaishoVtLst.svg": "割",
  "05272.svg": "割",
  "05273.svg": "剳",
  "05274.svg": "剴",
  "05275.svg": "創",

Now we have a way to find kanji from svg
- next is finding kanji information from kanji

### linking
```svg -> kanji -> kanji_info```

In [2]:
jouyou_kanji_info_file_path = "../data_raw/jouyou_kanji_information_all.csv"

import pandas as pd

df = pd.read_csv(filepath_or_buffer=jouyou_kanji_info_file_path, delimiter=';')
df.head()

,id,Kanji,Strokes,Grade,Kanji Classification,JLPT-test,Name of Radical,Radical Freq.,Reading within Joyo,Reading beyond Joyo,...,Right3sound,Right3freq,Right4sound,Right4freq,Right5sound,Right5freq,Right6sound,Right6freq,Right7sound,Right7freq
0,1,亜,7,7,象形 Pictographic,1,Ni,6,ア,NaN,...,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0
1,2,哀,9,7,会意 Com. Ideographic,1,"Kuchi, Kuchihen",70,アイ、あわ-れ、あわ-れむ,かな,...,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0
2,3,挨,10,7,形声 Phonetic,0,Tehen,89,アイ,NaN,...,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0
3,4,愛,13,4,会意 Com. Ideographic,3,"Kokoro, Risshinben, Shitagokoro",76,アイ,オ、いと、め,...,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0
4,5,曖,17,7,形声 Phonetic,0,"Nichi, Nichihen",38,アイ,NaN,...,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0

In [ ]:
def get_kanji_info(kanji_char):
  return df[df["Kanji"] == kanji_char]

In [8]:
get_kanji_info("激")

,id,Kanji,Strokes,Grade,Kanji Classification,JLPT-test,Name of Radical,Radical Freq.,Reading within Joyo,Reading beyond Joyo,...,Right3sound,Right3freq,Right4sound,Right4freq,Right5sound,Right5freq,Right6sound,Right6freq,Right7sound,Right7freq
503,504,激,16,6,形声 Phonetic,1,"Mizu, Sanzui, Shitamizu",118,ゲキ、はげ-しい,NaN,...,NaN,0,NaN,0,NaN,0,NaN,0,NaN,0